#!/bin/bash -e
#
# First-time init for Debian package squid proxy

# Create writable log file
for i in access.log cache.log store.log netdb.state; do
    f=/var/log/supervisor/$i
    if ! test -f $f; then
	echo "Creating missing file '$f'"
	touch $f
	chown proxy:proxy $f
    fi
done

# Silence warnings
echo 'bogus-package' > \
    "/etc/squid-deb-proxy/autogenerated/pkg-blacklist-regexp.acl"

# Run Debian package's init function
( set -x; . /usr/share/squid-deb-proxy/init-common.sh && pre_start; )
